# Generated by Django 5.2 on 2025-04-07 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("answered", "Answered"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("urgency", models.CharField(default="normal", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("guide", "Guide"),
                            ("video", "Video"),
                            ("article", "Article"),
                            ("tool", "Tool"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(upload_to="resources/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tags", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "query",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.query",
                    ),
                ),
                ("response", models.TextField()),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_satisfactory", models.BooleanField(default=False)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
